version: '3.8'

services:
  app:
    image: alkuluvut-front-dev
    build:
      context: ./frontend
      dockerfile: ./frontend/dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: alkuluvut-front-dev

  server:
    image: alkuluvut-back-dev
    build:
      context: ./backend
      dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3003:3003
    container_name: alkuluvut-back-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server
